"""empty message

Revision ID: 1a19d4d964e7
Revises: 740f2e809216
Create Date: 2023-09-07 14:10:26.254811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a19d4d964e7'
down_revision = '740f2e809216'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('annotation_task', schema=None) as batch_op:
        batch_op.alter_column('task_type',
               existing_type=sa.TEXT(),
               type_=sa.Enum('comparison_annotation'),
               existing_nullable=False)
        batch_op.alter_column('task_status',
               existing_type=sa.TEXT(),
               type_=sa.Enum('created', 'closed'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('annotation_task', schema=None) as batch_op:
        batch_op.alter_column('task_status',
               existing_type=sa.Enum('created', 'closed'),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('task_type',
               existing_type=sa.Enum('comparison_annotation'),
               type_=sa.TEXT(),
               existing_nullable=False)

    # ### end Alembic commands ###
