"""empty message

Revision ID: 32ef31a8cb55
Revises: 92668193c165
Create Date: 2023-09-01 18:18:49.296422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32ef31a8cb55'
down_revision = '92668193c165'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('annotation_task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('task_queue_sample_num', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('annotation_task', schema=None) as batch_op:
        batch_op.drop_column('task_queue_sample_num')

    # ### end Alembic commands ###
