"""empty message

Revision ID: 740f2e809216
Revises: 32ef31a8cb55
Create Date: 2023-09-01 18:56:38.774433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '740f2e809216'
down_revision = '32ef31a8cb55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('annotation_task', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_annotation_task_create_user'), ['create_user'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('annotation_task', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_annotation_task_create_user'))

    # ### end Alembic commands ###
