"""empty message

Revision ID: 92668193c165
Revises: 
Create Date: 2023-08-31 21:09:13.229146

"""
from alembic import op
import sqlalchemy as sa
import rlhf_annotation


# revision identifiers, used by Alembic.
revision = '92668193c165'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('annotation_record',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_uuid', sa.String(length=8), nullable=True),
    sa.Column('smaple_id', sa.Integer(), nullable=True),
    sa.Column('start_annotation_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('annotation_task',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=8), nullable=True),
    sa.Column('create_user', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('raw_data_path', sa.Text(), nullable=False),
    sa.Column('task_work_path', sa.Text(), nullable=False),
    sa.Column('total_sample_num', sa.Integer(), nullable=False),
    sa.Column('annotated_sample_num', sa.Integer(), nullable=False),
    sa.Column('in_progress_sample_num', sa.Integer(), nullable=False),
    sa.Column('task_queue_path', sa.Text(), nullable=False),
    sa.Column('in_progress_path', sa.Text(), nullable=False),
    sa.Column('all_samples_path', sa.Text(), nullable=False),
    sa.Column('task_type', sa.Text(), nullable=False),
    sa.Column('task_status', sa.Text(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('create_user'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('token_blocklist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('token_blocklist', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_token_blocklist_jti'), ['jti'], unique=False)

    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.Text(), nullable=False),
    sa.Column('password', sa.Text(), nullable=False),
    sa.Column('is_admin', rlhf_annotation.models.LiberalBoolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    with op.batch_alter_table('token_blocklist', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_token_blocklist_jti'))

    op.drop_table('token_blocklist')
    op.drop_table('annotation_task')
    op.drop_table('annotation_record')
    # ### end Alembic commands ###
